from .enums import *
from .jokers import *

ANTE_BASE_CHIPS = [
    [
        100,
        300,
        800,
        2000,
        5000,
        11000,
        20000,
        35000,
        50000,
        110000,
        560000,
        7200000,
        300000000,
        47000000000,
        2.9e13,
        7.7e16,
        8.6e20,
        4.2e25,
        9.2e30,
        9.2e36,
        4.3e43,
        9.7e50,
        1.0e59,
        5.8e67,
        1.6e77,
        2.4e87,
        1.9e98,
        8.4e109,
        2.0e122,
        2.7e135,
        2.1e149,
        9.9e163,
        2.7e179,
        4.4e195,
        4.4e212,
        2.8e230,
        1.1e249,
        2.7e268,
        4.5e288,
        4.8e309,
    ],
    [
        100,
        300,
        900,
        2600,
        8000,
        20000,
        36000,
        60000,
        100000,
        230000,
        1100000,
        14000000,
        600000000,
        94000000000,
        5.8e13,
        1.5e17,
        1.7e21,
        8.4e25,
        1.8e31,
        1.8e37,
        8.6e43,
        1.9e51,
        2.1e59,
        1.1e68,
        3.3e77,
        4.9e87,
        3.9e98,
        1.6e110,
        4.0e122,
        5.5e135,
        4.3e149,
        1.9e164,
        5.4e179,
        8.9e195,
        8.9e212,
        5.6e230,
        2.2e249,
        5.5e268,
        9.0e288,
        9.6e309,
    ],
    [
        100,
        300,
        1000,
        3200,
        9000,
        25000,
        60000,
        110000,
        200000,
        460000,
        2200000,
        29000000,
        1200000000,
        1.8e11,
        1.1e14,
        3.0e17,
        3.4e21,
        1.6e26,
        3.7e31,
        3.7e37,
        1.7e44,
        3.8e51,
        4.2e59,
        2.3e68,
        6.6e77,
        9.8e87,
        7.8e98,
        3.3e110,
        8.1e122,
        1.1e136,
        8.6e149,
        3.9e164,
        1.0e180,
        1.7e196,
        1.7e213,
        1.1e231,
        4.4e249,
        1.1e269,
        1.8e289,
        1.9e310,
    ],
]
BLIND_COLORS = {
    Blind.SMALL_BLIND: "#324ba0",
    Blind.BIG_BLIND: "#db9832",
    Blind.THE_HOOK: "#9c472d",
    Blind.THE_CLUB: "#bcca98",
    Blind.THE_PSYCHIC: "#e8c256",
    Blind.THE_GOAD: "#ad6193",
    Blind.THE_WINDOW: "#a8a296",
    Blind.THE_MANACLE: "#575757",
    Blind.THE_PILLAR: "#7a6855",
    Blind.THE_HEAD: "#a99eb2",
    Blind.THE_HOUSE: "#5d85a5",
    Blind.THE_WALL: "#835ba1",
    Blind.THE_WHEEL: "#6fbd82",
    Blind.THE_ARM: "#6765eb",
    Blind.THE_FISH: "#5183b8",
    Blind.THE_WATER: "#cbdfea",
    Blind.THE_MOUTH: "#a5748d",
    Blind.THE_NEEDLE: "#606d39",
    Blind.THE_FLINT: "#d6713f",
    Blind.THE_MARK: "#633b47",
    Blind.THE_EYE: "#5370dd",
    Blind.THE_TOOTH: "#a73933",
    Blind.THE_PLANT: "#779185",
    Blind.THE_SERPENT: "#5b9857",
    Blind.THE_OX: "#ad6025",
    Blind.AMBER_ACORN: "#f0a63a",
    Blind.VERDANT_LEAF: "#6aa588",
    Blind.VIOLET_VESSEL: "#8672da",
    Blind.CRIMSON_HEART: "#9f3c37",
    Blind.CERULEAN_BELL: "#459af6",
}
BLIND_INFO = {
    Blind.SMALL_BLIND: [1, 1, 3],
    Blind.BIG_BLIND: [1, 1.5, 4],
    Blind.THE_HOOK: [1, 2, 5],
    Blind.THE_CLUB: [1, 2, 5],
    Blind.THE_PSYCHIC: [1, 2, 5],
    Blind.THE_GOAD: [1, 2, 5],
    Blind.THE_WINDOW: [1, 2, 5],
    Blind.THE_MANACLE: [1, 2, 5],
    Blind.THE_PILLAR: [1, 2, 5],
    Blind.THE_HEAD: [1, 2, 5],
    Blind.THE_HOUSE: [2, 2, 5],
    Blind.THE_WALL: [2, 4, 5],
    Blind.THE_WHEEL: [2, 2, 5],
    Blind.THE_ARM: [2, 2, 5],
    Blind.THE_FISH: [2, 2, 5],
    Blind.THE_WATER: [2, 2, 5],
    Blind.THE_MOUTH: [2, 2, 5],
    Blind.THE_NEEDLE: [2, 1, 5],
    Blind.THE_FLINT: [2, 2, 5],
    Blind.THE_MARK: [2, 2, 5],
    Blind.THE_EYE: [3, 2, 5],
    Blind.THE_TOOTH: [3, 2, 5],
    Blind.THE_PLANT: [4, 2, 5],
    Blind.THE_SERPENT: [5, 2, 5],
    Blind.THE_OX: [6, 2, 5],
    Blind.AMBER_ACORN: [8, 2, 8],
    Blind.VERDANT_LEAF: [8, 2, 8],
    Blind.VIOLET_VESSEL: [8, 6, 8],
    Blind.CRIMSON_HEART: [8, 2, 8],
    Blind.CERULEAN_BELL: [8, 2, 8],
}
CARD_EDITION_CHANCES = {
    Edition.BASE: 92,
    Edition.POLYCHROME: 1.2,
    Edition.HOLOGRAPHIC: 2.8,
    Edition.FOIL: 4,
}
CARD_EDITION_CHANCES_GLOW_UP = {
    Edition.BASE: 68,
    Edition.POLYCHROME: 4.8,
    Edition.HOLOGRAPHIC: 11.2,
    Edition.FOIL: 16,
}
CARD_EDITION_CHANCES_HONE = {
    Edition.BASE: 84,
    Edition.POLYCHROME: 2.4,
    Edition.HOLOGRAPHIC: 5.6,
    Edition.FOIL: 8,
}
CARD_EDITION_CHANCES_ILLUSION = {
    Edition.BASE: 80,
    Edition.POLYCHROME: 3,
    Edition.HOLOGRAPHIC: 7,
    Edition.FOIL: 10,
}
CHALLENGE_SETUPS = {
    Challenge.THE_OMELETTE: ChallengeSetup(
        initial_jokers=([Egg()] * 5),
        banned_joker_types={
            ToTheMoon,
            Rocket,
            GoldenJoker,
            Satellite,
        },
        banned_vouchers={Voucher.SEED_MONEY, Voucher.MONEY_TREE},
    ),
    Challenge.FIFTEEN_MINUTE_CITY: ChallengeSetup(
        initial_jokers=[RideTheBus(is_eternal=True), Shortcut(is_eternal=True)],
        deck_cards=[
            Card(rank, suit)
            for suit in Suit
            for rank in [
                Rank.KING,
                Rank.KING,
                Rank.QUEEN,
                Rank.QUEEN,
                Rank.JACK,
                Rank.JACK,
                Rank.TEN,
                Rank.NINE,
                Rank.EIGHT,
                Rank.SEVEN,
                Rank.SIX,
                Rank.FIVE,
                Rank.FOUR,
            ]
        ],
    ),
    Challenge.RICH_GET_RICHER: ChallengeSetup(
        initial_vouchers={Voucher.SEED_MONEY, Voucher.MONEY_TREE}, starting_money=100
    ),
    Challenge.ON_A_KNIFES_EDGE: ChallengeSetup(
        initial_jokers=[CeremonialDagger(is_eternal=True)]
    ),
    Challenge.X_RAY_VISION: ChallengeSetup(),
    Challenge.MAD_WORLD: ChallengeSetup(
        initial_jokers=[
            Pareidolia(edition=Edition.NEGATIVE, is_eternal=True),
            BusinessCard(is_eternal=True),
        ],
        banned_blinds={Blind.THE_PLANT},
        deck_cards=[Card(rank, suit) for suit in Suit for rank in list(Rank)[5:]],
    ),
    Challenge.LUXURY_TAX: ChallengeSetup(hand_size=10),
    Challenge.NON_PERISHABLE: ChallengeSetup(
        banned_joker_types={
            GrosMichel,
            IceCream,
            Cavendish,
            TurtleBean,
            Ramen,
            DietCola,
            Seltzer,
            Popcorn,
            MrBones,
            InvisibleJoker,
            Luchador,
        },
        banned_blinds={Blind.VERDANT_LEAF},
    ),
    Challenge.MEDUSA: ChallengeSetup(
        initial_jokers=[MarbleJoker(is_eternal=True)],
        deck_cards=[
            Card(rank, suit, enhancement=(Enhancement.STONE if rank.is_face else None))
            for suit in Suit
            for rank in Rank
        ],
    ),
    Challenge.DOUBLE_OR_NOTHING: ChallengeSetup(
        deck_cards=[Card(rank, suit, seal=Seal.RED) for suit in Suit for rank in Rank]
    ),
    Challenge.TYPECAST: ChallengeSetup(banned_blinds={Blind.VERDANT_LEAF}),
    Challenge.INFLATION: ChallengeSetup(
        initial_jokers=[CreditCard()],
        banned_vouchers={Voucher.CLEARANCE_SALE, Voucher.LIQUIDATION},
    ),
    Challenge.BRAM_POKER: ChallengeSetup(
        initial_jokers=[Vampire(is_eternal=True)],
        initial_consumables=[
            Consumable(Tarot.THE_EMPRESS),
            Consumable(Tarot.THE_EMPEROR),
        ],
        initial_vouchers={Voucher.MAGIC_TRICK, Voucher.ILLUSION},
    ),
    Challenge.FRAGILE: ChallengeSetup(
        initial_jokers=[OopsAllSixes(edition=Edition.NEGATIVE, is_eternal=True)] * 2,
        banned_consumable_cards={
            Tarot.THE_MAGICIAN,
            Tarot.THE_EMPRESS,
            Tarot.THE_HEIROPHANT,
            Tarot.THE_CHARIOT,
            Tarot.THE_DEVIL,
            Tarot.THE_TOWER,
            Tarot.THE_LOVERS,
            Spectral.INCANTATION,
            Spectral.GRIM,
            Spectral.FAMILIAR,
        },
        banned_joker_types={MarbleJoker, Vampire, MidasMask, Certificate},
        banned_packs={Pack.STANDARD, Pack.JUMBO_STANDARD, Pack.MEGA_STANDARD},
        banned_tags={Tag.STANDARD},
        banned_vouchers={Voucher.MAGIC_TRICK, Voucher.ILLUSION},
        deck_cards=[
            Card(rank, suit, enhancement=Enhancement.GLASS)
            for suit in Suit
            for rank in Rank
        ],
    ),
    Challenge.MONOLITH: ChallengeSetup(
        initial_jokers=[
            Obelisk(is_eternal=True),
            MarbleJoker(edition=Edition.NEGATIVE, is_eternal=True),
        ]
    ),
    Challenge.BLAST_OFF: ChallengeSetup(
        initial_jokers=[Constellation(is_eternal=True), Rocket(is_eternal=True)],
        initial_vouchers={Voucher.PLANET_MERCHANT, Voucher.PLANET_TYCOON},
        banned_joker_types={Burglar},
        banned_vouchers={Voucher.GRABBER, Voucher.NACHO_TONG},
        discards_per_round=2,
        hands_per_round=2,
        joker_slots=4,
    ),
    Challenge.FIVE_CARD_DRAW: ChallengeSetup(
        initial_jokers=[CardSharp(), Joker()],
        banned_joker_types={Juggler, Troubadour, TurtleBean},
        discards_per_round=6,
        hand_size=5,
        joker_slots=7,
    ),
    Challenge.GOLDEN_NEEDLE: ChallengeSetup(
        initial_jokers=[CreditCard()],
        banned_joker_types={Burglar},
        banned_vouchers={Voucher.GRABBER, Voucher.NACHO_TONG},
        discards_per_round=6,
        hands_per_round=1,
        starting_money=10,
    ),
    Challenge.CRUELTY: ChallengeSetup(joker_slots=3),
    Challenge.JOKERLESS: ChallengeSetup(
        banned_blinds={Blind.CRIMSON_HEART, Blind.VERDANT_LEAF, Blind.AMBER_ACORN},
        banned_consumable_cards={Tarot.JUDGEMENT, Spectral.WRAITH, Spectral.THE_SOUL},
        banned_packs={Pack.BUFFOON, Pack.JUMBO_BUFFOON, Pack.MEGA_BUFFOON},
        banned_tags={
            Tag.UNCOMMON,
            Tag.RARE,
            Tag.NEGATIVE,
            Tag.FOIL,
            Tag.HOLOGRAPHIC,
            Tag.POLYCHROME,
            Tag.BUFFOON,
            Tag.TOP_UP,
        },
        banned_vouchers={Voucher.ANTIMATTER},
        joker_slots=0,
    ),
}
EDITION_COSTS = {
    Edition.BASE: 0,
    Edition.FOIL: 2,
    Edition.HOLOGRAPHIC: 3,
    Edition.POLYCHROME: 5,
    Edition.NEGATIVE: 5,
}
HAND_BASE_SCORE = {
    PokerHand.FLUSH_FIVE: [160, 16.0],
    PokerHand.FLUSH_HOUSE: [140, 14.0],
    PokerHand.FIVE_OF_A_KIND: [120, 12.0],
    PokerHand.STRAIGHT_FLUSH: [100, 8.0],
    PokerHand.FOUR_OF_A_KIND: [60, 7.0],
    PokerHand.FULL_HOUSE: [40, 4.0],
    PokerHand.FLUSH: [35, 4.0],
    PokerHand.STRAIGHT: [30, 4.0],
    PokerHand.THREE_OF_A_KIND: [30, 3.0],
    PokerHand.TWO_PAIR: [20, 2.0],
    PokerHand.PAIR: [10, 2.0],
    PokerHand.HIGH_CARD: [5, 1.0],
}
HAND_SCALING = {
    PokerHand.FLUSH_FIVE: [50, 3.0],
    PokerHand.FLUSH_HOUSE: [40, 4.0],
    PokerHand.FIVE_OF_A_KIND: [35, 3.0],
    PokerHand.STRAIGHT_FLUSH: [40, 4.0],
    PokerHand.FOUR_OF_A_KIND: [30, 3.0],
    PokerHand.FULL_HOUSE: [25, 2.0],
    PokerHand.FLUSH: [15, 2.0],
    PokerHand.STRAIGHT: [30, 3.0],
    PokerHand.THREE_OF_A_KIND: [20, 2.0],
    PokerHand.TWO_PAIR: [20, 1.0],
    PokerHand.PAIR: [15, 1.0],
    PokerHand.HIGH_CARD: [10, 1.0],
}
JOKER_BASE_COSTS = {
    Joker: 2,
    GreedyJoker: 5,
    LustyJoker: 5,
    WrathfulJoker: 5,
    GluttonousJoker: 5,
    JollyJoker: 3,
    ZanyJoker: 4,
    MadJoker: 4,
    CrazyJoker: 4,
    DrollJoker: 4,
    SlyJoker: 3,
    WilyJoker: 4,
    CleverJoker: 4,
    DeviousJoker: 4,
    CraftyJoker: 4,
    HalfJoker: 5,
    CreditCard: 1,
    Banner: 5,
    MysticSummit: 5,
    EightBall: 5,
    Misprint: 4,
    RaisedFist: 5,
    ChaosTheClown: 4,
    ScaryFace: 4,
    AbstractJoker: 4,
    DelayedGratification: 4,
    GrosMichel: 5,
    EvenSteven: 4,
    OddTodd: 4,
    Scholar: 4,
    BusinessCard: 4,
    Supernova: 5,
    RideTheBus: 6,
    Egg: 4,
    Runner: 5,
    IceCream: 5,
    Splash: 3,
    BlueJoker: 5,
    FacelessJoker: 4,
    GreenJoker: 4,
    Superposition: 4,
    ToDoList: 4,
    Cavendish: 4,
    RedCard: 5,
    SquareJoker: 4,
    RiffRaff: 6,
    Photograph: 5,
    ReservedParking: 6,
    MailInRebate: 4,
    Hallucination: 4,
    FortuneTeller: 6,
    Juggler: 4,
    Drunkard: 4,
    GoldenJoker: 6,
    Popcorn: 5,
    WalkieTalkie: 4,
    SmileyFace: 4,
    GoldenTicket: 5,
    Swashbuckler: 4,
    HangingChad: 4,
    ShootTheMoon: 5,
    JokerStencil: 8,
    FourFingers: 7,
    Mime: 5,
    CeremonialDagger: 6,
    MarbleJoker: 6,
    LoyaltyCard: 5,
    Dusk: 5,
    Fibonacci: 8,
    SteelJoker: 7,
    Hack: 6,
    Pareidolia: 5,
    SpaceJoker: 5,
    Burglar: 6,
    Blackboard: 6,
    SixthSense: 6,
    Constellation: 6,
    Hiker: 5,
    CardSharp: 6,
    Madness: 7,
    Seance: 6,
    Vampire: 7,
    Shortcut: 7,
    Hologram: 7,
    CloudNine: 7,
    Rocket: 6,
    MidasMask: 7,
    Luchador: 5,
    GiftCard: 6,
    TurtleBean: 6,
    Erosion: 6,
    ToTheMoon: 5,
    StoneJoker: 6,
    LuckyCat: 6,
    Bull: 6,
    DietCola: 6,
    TradingCard: 6,
    FlashCard: 5,
    SpareTrousers: 6,
    Ramen: 6,
    Seltzer: 6,
    Castle: 6,
    MrBones: 5,
    Acrobat: 6,
    SockAndBuskin: 6,
    Troubadour: 6,
    Certificate: 6,
    SmearedJoker: 7,
    Throwback: 6,
    RoughGem: 7,
    Bloodstone: 7,
    Arrowhead: 7,
    OnyxAgate: 7,
    GlassJoker: 6,
    Showman: 5,
    FlowerPot: 6,
    MerryAndy: 7,
    OopsAllSixes: 4,
    TheIdol: 6,
    SeeingDouble: 6,
    Matador: 7,
    Satellite: 6,
    Cartomancer: 6,
    Astronomer: 8,
    Bootstraps: 7,
    DNA: 8,
    Vagabond: 8,
    Baron: 8,
    Obelisk: 8,
    BaseballCard: 8,
    AncientJoker: 8,
    Campfire: 9,
    Blueprint: 10,
    WeeJoker: 8,
    HitTheRoad: 8,
    TheDuo: 8,
    TheTrio: 8,
    TheFamily: 8,
    TheOrder: 8,
    TheTribe: 8,
    Stuntman: 7,
    InvisibleJoker: 8,
    Brainstorm: 10,
    DriversLicense: 7,
    BurntJoker: 8,
    Canio: 20,
    Triboulet: 20,
    Yorick: 20,
    Chicot: 20,
    Perkeo: 20,
}
JOKER_EDITION_CHANCES = {
    Edition.BASE: 96,
    Edition.NEGATIVE: 0.3,
    Edition.POLYCHROME: 0.3,
    Edition.HOLOGRAPHIC: 1.4,
    Edition.FOIL: 2,
}
JOKER_EDITION_CHANCES_HONE = {
    Edition.BASE: 92,
    Edition.NEGATIVE: 0.3,
    Edition.POLYCHROME: 0.9,
    Edition.HOLOGRAPHIC: 2.8,
    Edition.FOIL: 4,
}
JOKER_EDITION_CHANCES_GLOW_UP = {
    Edition.BASE: 84,
    Edition.NEGATIVE: 0.3,
    Edition.POLYCHROME: 2.1,
    Edition.HOLOGRAPHIC: 5.6,
    Edition.FOIL: 8,
}
JOKER_BASE_RARITY_WEIGHTS = {Rarity.COMMON: 70, Rarity.UNCOMMON: 25, Rarity.RARE: 5}
JOKER_RARITIES = {
    Rarity.COMMON: [
        Joker,
        GreedyJoker,
        LustyJoker,
        WrathfulJoker,
        GluttonousJoker,
        JollyJoker,
        ZanyJoker,
        MadJoker,
        CrazyJoker,
        DrollJoker,
        SlyJoker,
        WilyJoker,
        CleverJoker,
        DeviousJoker,
        CraftyJoker,
        HalfJoker,
        CreditCard,
        Banner,
        MysticSummit,
        EightBall,
        Misprint,
        RaisedFist,
        ChaosTheClown,
        ScaryFace,
        AbstractJoker,
        DelayedGratification,
        GrosMichel,
        EvenSteven,
        OddTodd,
        Scholar,
        BusinessCard,
        Supernova,
        RideTheBus,
        Egg,
        Runner,
        IceCream,
        Splash,
        BlueJoker,
        FacelessJoker,
        GreenJoker,
        Superposition,
        ToDoList,
        Cavendish,
        RedCard,
        SquareJoker,
        RiffRaff,
        Photograph,
        ReservedParking,
        MailInRebate,
        Hallucination,
        FortuneTeller,
        Juggler,
        Drunkard,
        GoldenJoker,
        Popcorn,
        WalkieTalkie,
        SmileyFace,
        GoldenTicket,
        Swashbuckler,
        HangingChad,
        ShootTheMoon,
    ],
    Rarity.UNCOMMON: [
        JokerStencil,
        FourFingers,
        Mime,
        CeremonialDagger,
        MarbleJoker,
        LoyaltyCard,
        Dusk,
        Fibonacci,
        SteelJoker,
        Hack,
        Pareidolia,
        SpaceJoker,
        Burglar,
        Blackboard,
        SixthSense,
        Constellation,
        Hiker,
        CardSharp,
        Madness,
        Seance,
        Vampire,
        Shortcut,
        Hologram,
        CloudNine,
        Rocket,
        MidasMask,
        Luchador,
        GiftCard,
        TurtleBean,
        Erosion,
        ToTheMoon,
        StoneJoker,
        LuckyCat,
        Bull,
        DietCola,
        TradingCard,
        FlashCard,
        SpareTrousers,
        Ramen,
        Seltzer,
        Castle,
        MrBones,
        Acrobat,
        SockAndBuskin,
        Troubadour,
        Certificate,
        SmearedJoker,
        Throwback,
        RoughGem,
        Bloodstone,
        Arrowhead,
        OnyxAgate,
        GlassJoker,
        Showman,
        FlowerPot,
        MerryAndy,
        OopsAllSixes,
        TheIdol,
        SeeingDouble,
        Matador,
        Satellite,
        Cartomancer,
        Astronomer,
        Bootstraps,
    ],
    Rarity.RARE: [
        DNA,
        Vagabond,
        Baron,
        Obelisk,
        BaseballCard,
        AncientJoker,
        Campfire,
        Blueprint,
        WeeJoker,
        HitTheRoad,
        TheDuo,
        TheTrio,
        TheFamily,
        TheOrder,
        TheTribe,
        Stuntman,
        InvisibleJoker,
        Brainstorm,
        DriversLicense,
        BurntJoker,
    ],
    Rarity.LEGENDARY: [
        Canio,
        Triboulet,
        Yorick,
        Chicot,
        Perkeo,
    ],
}
NON_ETERNAL_JOKERS = {
    GrosMichel,
    IceCream,
    Cavendish,
    Popcorn,
    Luchador,
    TurtleBean,
    DietCola,
    Ramen,
    Seltzer,
    MrBones,
    InvisibleJoker,
}
NON_PERISHABLE_JOKERS = {
    RideTheBus,
    Runner,
    GreenJoker,
    RedCard,
    SquareJoker,
    CeremonialDagger,
    Constellation,
    Madness,
    Vampire,
    Hologram,
    Rocket,
    LuckyCat,
    FlashCard,
    SpareTrousers,
    Castle,
    GlassJoker,
    Obelisk,
    WeeJoker,
}
PROHIBITED_ANTE_1_TAGS = {
    Tag.NEGATIVE,
    Tag.STANDARD,
    Tag.METEOR,
    Tag.BUFFOON,
    Tag.HANDY,
    Tag.GARBAGE,
    Tag.ETHEREAL,
    Tag.TOP_UP,
    Tag.ORBITAL,
}
SHOP_BASE_CARD_WEIGHTS = {BalatroJoker: 20, Tarot: 4, Planet: 4}
SHOP_BASE_PACK_WEIGHTS = {
    Pack.ARCANA: 4,
    Pack.JUMBO_ARCANA: 2,
    Pack.MEGA_ARCANA: 0.5,
    Pack.CELESTIAL: 4,
    Pack.JUMBO_CELESTIAL: 2,
    Pack.MEGA_CELESTIAL: 0.5,
    Pack.SPECTRAL: 0.6,
    Pack.JUMBO_SPECTRAL: 0.3,
    Pack.MEGA_SPECTRAL: 0.07,
    Pack.STANDARD: 4,
    Pack.JUMBO_STANDARD: 2,
    Pack.MEGA_STANDARD: 0.5,
    Pack.BUFFOON: 1.2,
    Pack.JUMBO_BUFFOON: 0.6,
    Pack.MEGA_BUFFOON: 0.5,
}
TAG_PACKS = {
    Tag.BUFFOON: Pack.MEGA_BUFFOON,
    Tag.CHARM: Pack.MEGA_ARCANA,
    Tag.METEOR: Pack.MEGA_CELESTIAL,
    Tag.ETHEREAL: Pack.SPECTRAL,
    Tag.STANDARD: Pack.MEGA_STANDARD,
}
UPGRADED_EDITION_WEIGHTS = {
    Edition.FOIL: 12.5,
    Edition.HOLOGRAPHIC: 8.75,
    Edition.POLYCHROME: 3.75,
}
